hmcts/pcq-consolidation-service

lib/AI-Agent.xml

https://tools.hmcts.net/jira/browse/PCQ-184
Adding missing AIAgent XML file.
```
[ ] Yes
[x] No
```

PCQ-184: Adding AIAgent

---

charts/pcq-consolidation-service/Chart.yaml
charts/pcq-consolidation-service/values.aat.template.yaml
charts/pcq-consolidation-service/values.preview.template.yaml
charts/pcq-consolidation-service/values.yaml
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationApplication.java

PCQ-183
1. Changed the job to CronJob and added Schedule.
2. Scheduled the actual job for 18:00 hrs as per the LLD and set the PR and AAT jobs to run every 20 minutes.
3. Disabled concurrent executions of the cronjob.
```
[ ] Yes
[X ] No
```

PCQ_183 - Added cron schedule and disabled concurrent execution

---

charts/pcq-consolidation-service/Chart.yaml

PCQ-183
Updated charts version after flux changes.
```
[ ] Yes
[ X] No
```

PCQ-183 - Updated chart version after flux change

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationApplication.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationApplicationTest.java

PCQ-183
Added exit code in the main application class to terminate the job after execution. 
```
[ ] Yes
[ X] No
```

PCQ_183 - Added exit code in the main application to terminate the job

---

charts/pcq-consolidation-service/Chart.yaml

PCQ-183
Updated charts version to match the flux config.
```
[ ] Yes
[ X] No
```

PCQ_183 -Updated charts version

---

src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/model/PcqAnswerResponse.java
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceTestBase.java
src/integrationTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/util/ConsolidationServiceIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponent.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/controller/feign/PcqBackendFeignClient.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/controller/response/SubmitResponse.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/PcqBackendService.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/impl/PcqBackendServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponentTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/controllers/response/SubmitResponseTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/impl/PcqBackendServiceImplTest.java

PCQ_182
Added code, unit tests, integ test and functional test for the Pcq backend API call - addCaseForPcq
```
[ ] Yes
[X ] No
```

Pcq 182 add case to pcq

---

charts/pcq-consolidation-service/Chart.yaml

Consolidation service charts update.
```
[ ] Yes
[x] No
```

PCQ-181 Bump to charts to pickup s2s

---

Jenkinsfile_CNP

Correcting S2S_NAME
```
[ ] Yes
[x] No
```

PCQ-181 Correcting name for S2S

---

charts/pcq-consolidation-service/Chart.yaml

Bump charts to pickup new Jenkins config.
```
[ ] Yes
[x] No
```

PCQ-181 Bump charts to pick up new cnp config

---

charts/pcq-consolidation-service/Chart.yaml
charts/pcq-consolidation-service/values.preview.template.yaml
charts/pcq-consolidation-service/values.yaml

PCQ-181 removed S2S_Name from charts
```
[ ] Yes
[x] No
```

PCQ-181 removed S2S_Name from charts

---

src/main/resources/application.yaml

Remove GoR from config as it doesn't have a pcq extractor role defined yet.
```
[ ] Yes
[x] No
```

PCQ-181-Remove GrantOfRepresentation case type

---

charts/pcq-consolidation-service/Chart.yaml

Bump charts
```
[ ] Yes
[x] No
```

PCQ-181 Bump charts to rebuild job

---

charts/pcq-consolidation-service/Chart.yaml
src/functionalTest/resources/application-functional.yaml
src/main/resources/application.yaml

Update config to use env parameters / vault values.
```
[ ] Yes
[x] No
```

PCQ-181 Put back env variables in config.

---

src/main/resources/application.yaml

Amending client details
```
[ ] Yes
[x] No
```

PCQ-181 Amending client details

---

src/main/resources/application.yaml

Update application yaml
```
[ ] Yes
[x] No
```

PCQ-181 Update application.yaml

---

src/main/resources/application.yaml

Change to pickup idam secret using vault value.
```
[ ] Yes
[x] No
```

PCQ-181 Revert code to use env variable

---

src/main/resources/application.yaml

Enable Probate cases.
```
[ ] Yes
[x] No
```

PCQ-181: Add probate cases.

---

charts/pcq-consolidation-service/Chart.yaml
charts/pcq-consolidation-service/values.yaml
src/main/resources/bootstrap.yaml

PCQ-333
Added Application Insight changes
```
[ ] Yes
[ X] No
```

PCQ_333_Changes to enable Application Insights

---

Jenkinsfile_CNP
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
src/functionalTest/resources/application-functional.yaml
src/integrationTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/util/ConsolidationServiceIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponent.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/controller/feign/PcqBackendFeignClient.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/controller/response/PcqAnswerResponse.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/controller/response/PcqAnswers.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/controller/response/PcqRecordWithoutCaseResponse.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/impl/PcqBackendServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponentTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/controllers/response/PcqAnswerResponseTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/controllers/response/PcqAnswersTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/controllers/response/PcqRecordWithoutCaseResponseTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/impl/PcqBackendServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/utils/JsonFeignResponseUtilTest.java

PCQ-513
Modified the service call - getPcqWithoutCase - to the new API endpoint of getPcqRecordWithoutCase
Updated the unit tests and integration tests.
```
[ ] Yes
[X ] No
```

PCQ_513 Modified the call to getPcqWithoutCase to the new API

---

charts/pcq-consolidation-service/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-515
PCQ-515 Bump charts to align with flux config
```
[ ] Yes
[x] No
```

PCQ-515 Bump charts to align with flux config

---

build.gradle
charts/pcq-consolidation-service/Chart.yaml
config/owasp/suppressions.xml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PCQ-488
Updated to include Divorce, CMC and SSCS configuration.
```
[ ] Yes
[x] No
```

PCQ-488: adding config for sscs, divorce and cmc.

---

bin/env_variables_all.txt
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PCQ-488
Update to correct mapping for CMC Pcq ID fields.
```
[ ] Yes
[x] No
```

PCQ-488 Update to fix field mapping for CMC pcqId

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApi.java

https://tools.hmcts.net/jira/browse/PCQ-488
More logging to test PCQ issue.
```
[ ] Yes
[x] No
```

PCQ-488 Update to add logging

---

config/owasp/suppressions.xml

Fix nightly build by updating supression with false positive.
```
[ ] Yes
[x] No
```

PCQ-1234 Fix nightly build

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponent.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponentTest.java

https://tools.hmcts.net/jira/browse/PCQ-1234
Update to fix sonarqube quality issue with three bugs showing even though they didn't exist in previous builds...
```
[ ] Yes
[x] No
```

PCQ-1234: Update to fix SonarQube build.

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponent.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponentTest.java

Reinstate hasBody check as this is still giving the following error
A "NullPointerException" could be thrown; "pcqWithoutCaseResponse" is nullable here
```
[ ] Yes
[x] No
```

PCQ-1234 Update to improve code coverage.

---

build.gradle
charts/pcq-consolidation-service/Chart.yaml
charts/pcq-consolidation-service/requirements.yaml

PCQ-647
Updated the CCD API to v4.7.3
```
[ ] Yes
[X ] No
```

PCQ-647 - Updated CCD API to v4.7.3

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponent.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/utils/LoggingSummaryUtils.java

PCQ-712
The service summary count for online records is not getting displayed because the service map key was case-sensitive.
```
[ ] Yes
[ X] No
```

PCQ_712 - Fix to the service summary count

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-740
Update to fix vulnerability with older version of httpclient.
```
[ ] Yes
[x] No
```

PCQ-740: Update to fix dependancy vulnerability.

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
src/functionalTest/resources/JsonTestFiles/SecondSubmitAnswerWithDcn.json

https://tools.hmcts.net/jira/browse/PCQ-758
Update to upgrade Spring boot and resolve some older suppressions.
```
[ ] Yes
[x] No
```

PCQ-758: Update to upgrade springboot.

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java

https://tools.hmcts.net/jira/browse/PCQ-814
Fix to vulnerability in code.
```
[ ] Yes
[x] No
```

PCQ-814: Fix to vulnerability in tomcat.

---

build.gradle
config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-783
Update libraries.
```
[ ] Yes
[x] No
```

Pcq 783 update consolidation service libraries

---

src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java

https://tools.hmcts.net/jira/browse/PCQ-1234
Config update to fix functional test.
```
[ ] Yes
[x] No
```

PCQ-1234 Config update to fix functional test after environment issues.

---

compose/backend.yml
docker/ccd-database/Dockerfile
src/functionalTest/resources/application-functional.yaml
src/integrationTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/config/ServiceConfigTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApiTest.java
src/integrationTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/config/ServiceConfigItem.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApi.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponentTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/config/ServiceConfigHelper.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/config/ServiceConfigProviderTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApiTest.java

https://tools.hmcts.net/jira/browse/PCQ-829
Update to add custom DCN path for elastic search to find SSCS cases.
```
[ ] Yes
[x] No
```

PCQ-829: Update of files to add SSCS DCN configuration.

---

charts/pcq-consolidation-service/Chart.yaml
charts/pcq-consolidation-service/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
src/functionalTest/resources/JsonTestFiles/SecondSubmitAnswerWithDcn.json

https://tools.hmcts.net/jira/browse/PCQ-840
Helm charts upgrade and minor change to functional test data following elastic search failures.
```
[ ] Yes
[x] No
```

PCQ-840-UpdateHelmCharts

---

bin/env_variables_all.txt
bin/idam-client-setup.sh
bin/idam-role-assignable.sh
bin/idam-role.sh
compose/README.md

https://tools.hmcts.net/jira/browse/PCQ-874
Remove IdAM Admin password from developer docker scripts.
```
[ ] Yes
[x] No
```

PCQ-874: Update to remove IdAM admin password from scripts.

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-887
https://tools.hmcts.net/jira/browse/PCQ-889
CVE fixes
```
[ ] Yes
[x] No
```

fix for CVEs

---

src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceTestBase.java
src/functionalTest/resources/JsonTestFiles/SecondSubmitAnswerWithDcn.json

https://tools.hmcts.net/jira/browse/PCQ-1003
Fix to functional tests.
```
[ ] Yes
[x] No
```

PCQ-1003: Update to fix functional tests.

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1025
Did two changes one build.gradle to change the vesion for Spring framework and springFramework.boot
and also added a new version for jakarta jar
Changed in supppressions.xml file  as well
```
[ ] Yes
[x] No
```

fix pcq-consolidation vulnerability

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/PCQ-1025
Upgraded to Spring Framework 2.5.3 and Gradle 6.8
```
[ ] Yes
[x] No
```

springFrameworkUpgrade

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/PCQ-988
This change is about syncing other branches with master for pcq-consolidation service
```
[ ] Yes
[x] No
```

Sync Branches with master

---

charts/pcq-consolidation-service/values.preview.template.yaml
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java

https://tools.hmcts.net/jira/browse/PCQ-1095
This change is for functional test is failing after optout change . At the moment  we are just doing a temporary change. Once we get delete end point we will revert back and fix this functional test accordingly.
```
[ ] Yes
[x] No
```

Pcq 1095 fix functional test

---

compose/backend.yml
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceTestBase.java

https://tools.hmcts.net/jira/browse/PCQ-1114
Functional test change
```
[ ] Yes
[x] No
```

PCQ-1114Functional Test

---

compose/backend.yml

https://tools.hmcts.net/jira/browse/PCQ-1020
This change is to run consolidation service locally.
```
[ ] Yes
[x] No
```

PCQ-1020Consolidation Service

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1120
This change is about Dependency check
```
[ ] Yes
[x] No
```

Pcq 1120 dependency check

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceTestBase.java

https://tools.hmcts.net/jira/browse/PCQ-1114
Fix Consolidation Service Functional Tests during nightly pipeline.
```
[ ] Yes
[x] No
```

Pcq 1114 fix functional tests again

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/PCQ-1190
This change is disable Fortify Scan
```
[ ] Yes
[ x] No
```

PCQ-1190Disable Consolidation

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1195
This change is to upgrade log4j to 2.15.0
```
[ ] Yes
[x] No
```

PCQ-1190 log4j upgrade

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/PCQ-1212
This change is to Enable fortify Scan again
```
[ ] Yes
[x] No
```

PCQ-1212 Enable Fortify Scan

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/PCQ-1134
Update pcq-consolidation-service to Gradle 7.2
Summary of issues fixed :-
**Error:**	Could not set unknown property 'configDir' for extension 'checkstyle' of type org.gradle.api.plugins.quality.CheckstyleExtension.
**Fix:**	Replace 'configDir' with 'configDirectory'
**Error:** 	Could not find method compile() ...
**Fix:**	Replace 'compile' with 'implementation'		(in dependencies block)
Replace 'estCompile' with 'estImplementation'	(throughout build.gradle)
**Error:**	Entry xxxxxxxx is a duplicate but no duplicate handling strategy has been set.
**Fix:**	Add rootProject.tasks.named .... duplicatesStrategy = 'include'
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

PCQ‐1134: Update pcq-consolidation-service to Gradle 7.2

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1236
This change is about hmcts library upgrade
```
[ ] Yes
[x] No
```

PCQ-1236 HMCTS library upgrade

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1338
This change is to fix dependency check
```
[ ] Yes
[x] No
```

PCQ-1338 Dependency check fixed

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1191
Change version of tomcat-embed to 9.0.59
```
[ ] Yes
[x] No
```

Changing version of Tomcat-embed

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-959
This change is to upgrade Jackson-databind
```
[ ] Yes
[x] No
```

PCQ-959 jackson-databind upgrade

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/PcqBackendService.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponentTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponentUtil.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApiTest.java

https://tools.hmcts.net/jira/browse/PCQ-819
This change is to reduce code smell in consolidation service
```
[ ] Yes
[x] No
```

Consolidation code smell fix

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1421
Remove suppressions and update io.netty to 4.1.76
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

PCQ-1421-remove-redundant-vulnerability-suppressions-2

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1333
This change is to upgrade other libraries
```
[ ] Yes
[x] No
```

Pcq 1333 consolidation

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-790
This change is to fix spring-security related issue.
```
[ ] Yes
[x] No
```

PCQ-790 Dependency check fix

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-876
This change is to fix dependency check related to CVE-2022-22978
```
[ ] Yes
[x] No
```

PCQ-876 Dependency check fix

---

renovate/configure/renovate.json

https://tools.hmcts.net/jira/browse/PCQ-1335
This change has been done to configure renovate
```
[ ] Yes
[x] No
```

PCQ-1335configure renovate

---

charts/pcq-consolidation-service/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-941
This change is to fix dependency check
```
[ ] Yes
[x] No
```

PCQ-914 Dependency check fixed

---

.dependabot/dependabot.yml

https://tools.hmcts.net/jira/browse/PCQ-896
This change is to upgrade dependabot
```
[ ] Yes
[x] No
```

PCQ-896 Upgrade dependabot

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1456
This change is to fix Dependency check.
```
[ ] Yes
[x] No
```

PCQ-1456dependency check fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-935
This change is to upgrade libraries
```
[ ] Yes
[x] No
```

PCQ-935 Libraries upgrade

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1529
This change is to fix CVE-2022-25857
```
[ ] Yes
[x] No
```

PCQ-1529 Sankeyaml dependency check fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1537
This change is to fix dependency check CVE-2022-42003 and CVE-2022-42004
```
[ ] Yes
[x] No
```

PCQ-1537dependency check fix

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/PCQ-1536
This change is to disable nightly build during weekend
```
[ ] Yes
[x] No
```

PCQ-1536 Disable nightly build during weekend

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1596
This change is to fix dependency check spring-security and tomcat-embed
```
[ ] Yes
[x] No
```

PCQ-1596 dependency check fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1600
This change is to upgrade libraries for PRs created by dependabot and renovate
```
[ ] Yes
[x] No
```

PCQ-1600upgrading libraries

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1600
This change is for upgrading libraries
```
[ ] Yes
[x] No
```

PCQ-1600Upgrading more libraries

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1620
This change is to suppress CVE
```
[ ] Yes
[x] No
```

PCQ-1620 Suppressing CVE

---

build.gradle
charts/pcq-consolidation-service/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-1626
This change is to fix CVE-2022-41881, CVE-2022-41915
```
[ ] Yes
[x] No
```

PCQ-1626Dependency Check fix

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1629
This change is to suppress CVE
```
[ ] Yes
[x] No
```

PCQ-1629suppressing CVE

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1631
This change is to fix CVE-2022-45143
```
[ ] Yes
[x] No
```

PCQ-1631dependency check fix

---

charts/pcq-consolidation-service/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-1622
This change is for helm chart-job upgrade
```
[ ] Yes
[x] No
```

PCQ-1622 chart-job upgrade

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1649
This change is to fix CVE-2022-45688
```
[ ] Yes
[x] No
```

PCQ-1649Fix CVE-2022-45688

---

.github/dependabot.yml
build.gradle
charts/pcq-consolidation-service/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-1648
Configuring dependabot on particular day
```
[ ] Yes
[x] No
```

PCQ-1648configuring dependabot on particular day

---

charts/pcq-consolidation-service/Chart.yaml

https://tools.hmcts.net/jira/browse/PCQ-1645
Bump Chart  version
```
[ ] Yes
[x] No
```

Bump  Chart.yaml version

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1718
This change is to upgrade springFramework.boot to 3.0.6
```
[ ] Yes
[x] No
```

PCQ-1718 upgrade spring Boot library

---

src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/ccd/util/CaseCreator.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponent.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApi.java

https://tools.hmcts.net/jira/browse/PCQ-1608
Remove unnecessary logs.
```
[ ] Yes
[x] No
```

Remove unnecessary logs.

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1656
This change is to upgrade snakeyml library version to 2.0
```
[ ] Yes
[x] No
```

PCQ-1656 snakeyml library upgrade

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PCQ-1757
This change is to suppress CVE-2023-35116
```
[ ] Yes
[x] No
```

PCQ-1757 suppress CVE-2023-35116

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/postdeploy/ConsolidationServiceFunctionalTest.java

[PCQ-1762](https://tools.hmcts.net/jira/browse/PCQ-1762)
Bump versions
```
[ ] Yes
[x] No
```

PCQ-1762 bump versions

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1783
This is to fix dependency check 
```
[ ] Yes
[x] No
```

PCQ-1783 Dependency check

---

build.gradle
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/security/SecurityConfiguration.java

https://tools.hmcts.net/jira/browse/PCQ-1783
This change is to fix [CVE-2023-34035]
```
[ ] Yes
[ x No
```

PCQ-1783 CVE fix

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1807
This change is to fix CVE-2023-41080
```
[ ] Yes
[x] No
```

PCQ-1807 tomcat upgrade for CVE CVE-2023-41080

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/impl/PcqBackendServiceImpl.java

https://tools.hmcts.net/jira/browse/PCQ-1782
This is to add contentType headers in log
```
[ ] Yes
[x] No
```

PCQ-1782 added contentType headers

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/PCQ-1806
To change renovate configuration
```
[ ] Yes
[x] No
```

PCQ-1806 renovate configuration

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/service/impl/PcqBackendServiceImpl.java

https://tools.hmcts.net/jira/browse/PCQ-1782
Logging header
```
[ ] Yes
[x] No
```

PCQ-1782 logging header

---

config/owasp/suppressions.xml

Suppress CVE to fix pipeline
```
[ ] Yes
[x] No
```

suppress CVE-2023-4586

---

charts/pcq-consolidation-service/Chart.yaml
charts/pcq-consolidation-service/values.preview.template.yaml
src/integrationTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/config/ServiceConfigTest.java
src/integrationTest/resources/application.yaml
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/utils/LoggingSummaryUtils.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PCQ-1821
This change is to add new caseType Civil in consolidation service
```
[ ] Yes
[x] No
```

PCQ-1821 adding new case Type civil  for civil-citizen-ui service

---

lib/applicationinsights.json

https://tools.hmcts.net/jira/browse/PCQ-1750
Log 1% of health message
```
[ ] Yes
[x] No
```

PCQ-1750 log 1% of health message

---

build.gradle

https://tools.hmcts.net/jira/browse/PCQ-1849
This change is to fix CVE-2023-34053 and CVE-2023-34055 through spring framework upgrade
```
[ ] Yes
[x] No
```

PCQ-1849 spring framework upgrade

---

build.gradle

Upgrade logback dependency
```
[ ] Yes
[x] No
```

Upgrade dependency logback

---

charts/pcq-consolidation-service/Chart.yaml
charts/pcq-consolidation-service/values.yaml

https://tools.hmcts.net/jira/browse/PCQ-1878
Enable spotInstance
```
[ ] Yes
[x] No
```

PCQ-1878 Enable spotInstance

---

build.gradle

Bump pitest junit plugin to fix failing mutation tests

Bump pitest junit plugin

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/pcqconsolidationservice/ccd/util/CaseCreator.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationApplication.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationComponent.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/security/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdAuthenticator.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdAuthenticatorFactory.java
src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApi.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdAuthenticatorFactoryTest.java
src/test/java/uk/gov/hmcts/reform/pcqconsolidationservice/services/ccd/CcdClientApiTest.java

https://tools.hmcts.net/jira/browse/PCQ-1651
Address code smells raised by sonar lint

PCQ-1651 address code smells

---

src/main/java/uk/gov/hmcts/reform/pcqconsolidationservice/ConsolidationApplication.java

Adding trace
```
[ ] Yes
[x] No
```

adding trace

---

config/owasp/suppressions.xml

Remove unnecessary suppression
```
[ ] Yes
[x] No
```

remove-unnecessary-suppression

---

.github/CODEOWNERS

https://tools.hmcts.net/jira/browse/PCQ-1978
Added code owners
```
[ ] Yes
[x] No
```

PCQ-1978 CODEOWNERS

---

SECURITY.md

https://tools.hmcts.net/jira/browse/PCQ-1979
Add Security.md file
```
[ ] Yes
[x] No
```

PCQ-1979 Create SECURITY.md

---

Dockerfile

https://tools.hmcts.net/jira/browse/PCQ-1984
Change to non root user
```
[ ] Yes
[x] No
```

PCQ-1984 change to non-root hmcts user

---

charts/pcq-consolidation-service/Chart.yaml

Bump chart to oci version
```
[ ] Yes
[ ] No
```

Bump chart version to oci version
